"""
Auto-generated Python script for calling exported Julia/Reactant function via EnzymeJAX.

This script was generated by Reactant.Serialization.export_to_enzymejax().
"""

from enzyme_ad.jax import hlo_call
import jax
from jax.sharding import PartitionSpec as P
import jax.numpy as jnp
import numpy as np
import os

# Get the directory of this script
_script_dir = os.path.dirname(os.path.abspath(__file__))

# Load the MLIR/StableHLO code
with open(os.path.join(_script_dir, "my_square_0.mlir"), "r") as f:
    _hlo_code = f.read()

def load_inputs():
    """Load the example inputs that were exported from Julia."""
    npz_data = np.load(os.path.join(_script_dir, "my_square_0_inputs.npz"))
    inputs = [npz_data['arr_1']]
    return tuple(inputs)
    

@jax.jit
def run_my_square(arg1):
    """
    Call the exported Julia function via EnzymeJAX.

    Args:
        arg1: Array of shape (4,) and dtype float32. Path: arg.1

    Returns:
        The result of calling the exported function.

    Note:
        All inputs must be in row-major (Python/NumPy) order. If you're passing
        arrays from Julia, make sure to transpose them first using:
        `permutedims(arr, reverse(1:ndims(arr)))`
    """
    assert arg1.dtype == np.dtype('float32'), f"Expected dtype of arg1 to be float32. Got {arg1.dtype} (path: arg.1)"
    assert arg1.shape == (4,), f"Expected shape of arg1 to be (4,). Got {arg1.shape} (path: arg.1)"
    return hlo_call(
        arg1,
        source=_hlo_code,
    )

if __name__ == "__main__":
    # Load the example inputs
    (arg1,) = load_inputs()
    # Convert inputs to jax arrays
    arg1 = jnp.asarray(arg1)

    # Run the function
    print("Running my_square...")
    result = run_my_square(arg1)
    print("Result:", result)
